 version: "3"
 
 services:
  
  backend:
    build:
      context: .
      args:
        ACCESS_KEY: ${ACCESS_KEY}
        SECRET_KEY: ${SECRET_KEY}
    image: backend:latest
    restart: always
    ports:
      - 8080:8080
  frontend:
    image: frontend:latest
    restart: always
    ports:
      - 3000:3000
    
